name: Build and Release APK
on:
  push:
    branches:
      - main
jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Cache Gradle
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Get app version info
        run: |
          echo "VERSION_NAME=$(grep versionName ~/.app/build.gradle | awk '{print $2}' | sed \"s/\'//g\")" >> $GITHUB_ENV
          echo "VERSION_CODE=$(grep versionCode ~/.app/build.gradle | awk '{print $2}' | sed \"s/\\r//\")" >> $GITHUB_ENV
          echo "PACKAGE_NAME=$(grep applicationId ~/.app/build.gradle | awk '{print $2}' | sed \"s/\'//g\")" >> $GITHUB_ENV
          echo "TAG_NAME=v${{ env.VERSION_CODE }}" >> $GITHUB_ENV
      - name: Build with Gradle
        run: |
          chmod +x gradlew
          ./gradlew assembleDebug
          ls app/build/outputs/apk/debug/
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.TAG_NAME }}
          release_name: Release v${{ env.VERSION_CODE }}
          body: |
            Release version v${{ env.VERSION_NAME }}
          draft: false
          prerelease: false
      - name: Upload APK
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: app/build/outputs/apk/debug/app-debug.apk
          asset_name: myDaggerHilt_${{ env.VERSION_CODE }}_${{ env.VERSION_NAME }}.apk
          asset_content_type: application/vnd.android.package-archive
