name: Build and Release APK
on:
  push:
    branches:
      - main
jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Cache Gradle
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Get version
        id: get_version
        run: |
          echo "::set-output name=code::$(grep versionCode buildSrc/src/main/java/Dependencies.kt | awk '{print $5}')"
          echo "::set-output name=name::$(grep versionName buildSrc/src/main/java/Dependencies.kt | awk '{print $5}' | tr '"' ' ' | tr -d " ")"
      - name: Get tag name
        id: get_tag
        run: echo "::set-output name=name::v${{ steps.get_version.outputs.name }}"
      - name: Get release name
        id: get_release
        run: echo "::set-output name=name::v${{ steps.get_version.outputs.name }}"
      - name: Build with Gradle
        run: |
          chmod +x gradlew
          ./gradlew assembleDebug
          ls app/build/outputs/apk/debug/
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.get_tag.outputs.name }}
          release_name: ${{ steps.get_release.outputs.name }}
          body: |
            Release version ${{ env.VERSION_NAME }}
          draft: false
          prerelease: false
      - name: Upload APK
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: app/build/outputs/apk/debug/app-debug.apk
          asset_name: mydaggerhilt_${{ steps.get_version.outputs.code }}_${{ steps.get_version.outputs.name }}.apk
          asset_content_type: application/vnd.android.package-archive
